vector_db:
  index_name: "agenticsystem"

embedding_model:
  provider: "huggingface"
  model_name: "sentence-transformers/all-MiniLM-L6-v2"

retriever:
  top_k: 3
  score_threshold: 0.5

llm:
  provider: "groq"
  model_name: "llama-3.1-8b-instant"
  temperature: 0.2   

tools:
  tavily:
    max_results: 5   